### ISSUE TITLE
Identifier not found "stTLSv1_1" #1

### ISSUE THREAD

**Issue by JacoFourie** [Al-Muhandis/fp-telegram#1]
Hi. I want to test the library on Raspberry Pi. I get this error when I compile the package. If I comment it out it compiles but I am not sure what will break if that is not there.

![image](https://user-images.githubusercontent.com/17771641/63655052-26f8e600-c783-11e9-845e-589306e0f785.png)

**Comment by Al-Muhandis** [comment]
Hi! You can try to comment this. But can you specify more details: Lazarus and FPC version, OS and CPU target etc?

**Comment by JacoFourie** [comment]
Hi, If I comment it out it compiles and runs but when it runs I get SSL errors.

I tried the project on Windows and there it works 100%. I then tried it on The Raspbarian Desktop in a virtual machine. There I get the same error that the variable does not exist.

I then tried it on Debian Desktop. There it compiles but I get SSL error also.

On Raspberry Pi I use it on Raspbian Buster (Debian 10) and FPC is 3.3.1 and Lazarus is 2.0.1

**Comment by JacoFourie** [comment]
Here I comment it out

![image](https://user-images.githubusercontent.com/17771641/63808671-c9020500-c920-11e9-88ba-3101a3f4d5ce.png)

Then I get the SSL error.

![image](https://user-images.githubusercontent.com/17771641/63808919-57768680-c921-11e9-8b14-835ad5ba001f.png)

**Comment by JacoFourie** [comment]
If you don't have a Raspberry Pi you can download the Desktop and run it in a VM

https://www.raspberrypi.org/downloads/raspberry-pi-desktop/

**Comment by Al-Muhandis** [comment]
I meant to comment out the whole procedure.

```
procedure TTelegramSender.HttpClientGetSocketHandler(Sender: TObject;
  const UseSSL: Boolean; out AHandler: TSocketHandler);
begin
  {$IFDEF LINUX}
    //if UseSSL then begin
    //  AHandler:=TSSLSocketHandler.Create;
    //  TSSLSocketHandler(AHandler).SSLType:=stTLSv1_1;  // <--
    //end;
  {$ENDIF}
end;  

 ```

**Comment by JacoFourie** [comment]
Nope. Still get a SSL error.

Error: [HTTPPostJSON] ESSLSocketError: No SSL Socket support compiled in.
Please include opensslsockets unit in program and recompile it.

**Comment by Al-Muhandis** [comment]
@JacoFourie please try last commit

**Comment by JacoFourie** [comment]
@Al-Muhandis I did comment it out. I then get that error 

Error: [HTTPPostJSON] ESSLSocketError: No SSL Socket support compiled in.
Please include opensslsockets unit in program and recompile it.

**Comment by JacoFourie** [comment]
@Al-Muhandis I get the same error with the commit from 7 hours ago.

Error: [HTTPPostJSON] ESSLSocketError: No SSL Socket support compiled in.
Please include opensslsockets unit in program and recompile it.

It wants SSL but can not find it.

**Comment by Al-Muhandis** [comment]
@JacoFourie Are you sure you tried the latest commit https://github.com/Al-Muhandis/fp-telegram/commit/4154e00da2a204420974f0f2ecaa89050a412ba6 / https://github.com/Al-Muhandis/fp-telegram ?

**Comment by JacoFourie** [comment]
Yes

![image](https://user-images.githubusercontent.com/17771641/63888907-2a3cdd80-c9e0-11e9-86cd-4277b8880641.png)

**Comment by Al-Muhandis** [comment]
@JacoFourie Did you tried to add `opensslsockets` unit in `tgsendertypes.pas` ?
```
implementation

uses
  jsonparser, jsonscanner{$IFDEF ExplSSL}, sslsockets, fpopenssl{$ENDIF}, opensslsockets
  ;   
```

**Comment by JacoFourie** [comment]
It is already included. If you include it again you get an error that it is already included.

I got Telegram working using Synapse. Your code still does not work but I gave up on it. I just wanted to send a message. 

Using Synapse it is very easy. 

https://medium.com/@xabaras/sending-a-message-to-a-telegram-channel-the-easy-way-eb0a0b32968

https://api.telegram.org/bot[BOT_API_KEY]/sendMessage?chat_id=[MY_CHANNEL_NAME]&text=[MY_MESSAGE_TEXT]

All you do is an HTTPS get post with that string and the message is sent.

Thanks for the effort, but I gave up on it.

Regards.
